### ISSUE TITLE
[FEAT] 홈 관련 API 구현

### ISSUE THREAD

**Issue by PgmJun** [TeamCafebara/Cafebara-BE#15]
## Description 📝
홈 뷰에서 사용되는 API 구현

## To-Do ☑️
- [ ] [직원] 홈 뷰 내에 근무 캘린더 조회 [담당자: @PgmJun]
- [ ] 유저 본인 이름 조회 [담당자: @PgmJun]
- [ ] [사장] 홈 뷰 내에 근무직원 조회 [담당자: @PgmJun]
- [ ] 속해있는 카페 리스트 조회 [담당자: @yeseul106 ]
- [ ] 카페 공지 사항 조회 [담당자: @KWY0218]

## Reference 📚
https://www.notion.so/cafebara/SERVER-1adc9a4125d34ce3845c5a801a06fa73
